# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f060c6c60e6aeac7712ff872317768191037e580dbd37d5409cc5d5f7b11802efded255787e5779d5b2ce91a8d9e1c7d3c36f6842c624ff801025b686ae554d8

test:
  secret_key_base: 7d3caa313464d5bf58d598f8f86d19ce60f0d88fd6911e6623fe83792fce65b021bf14a0a4f1a3211ef4f63a5526ecd551029ab99c2af5afa74cd66de5e17dc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
